language: go
go:
  - "1.10"
before_install:
  - "go get -u -v github.com/golang/dep"
  - "go install github.com/golang/dep"
  - "go get -u -v -t ./..."
  - "$GOPATH/bin/dep ensure -v"
script: go test -v ./...
