language: go
go:
  - "1.10"
before_install:
  - "go get -u -v github.com/golang/dep"
  - "go build -o dep github.com/golang/dep/cmd/dep"
  - "go get -u -v -t ./..."
  - "./dep ensure -v"
script: go test -v ./...
