Document: st
Title: Debian st Manual
Author: <insert document author here>
Abstract: This manual describes what st is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/st/st.sgml.gz

Format: postscript
Files: /usr/share/doc/st/st.ps.gz

Format: text
Files: /usr/share/doc/st/st.text.gz

Format: HTML
Index: /usr/share/doc/st/html/index.html
Files: /usr/share/doc/st/html/*.html
