package config

const DefaultConfig string = `
stimmtausch:
  version: 1

  server_types:
    muck:
      name: "TinyMUCK, FuzzballMUCK, etc."
      connect_string: "connect $username $password"
      disconnect_string: "QUIT"
  servers:
    spr:
      host: muck.sprmuck.org
      port: 23551
      ssl: true
      insecure: true
      type: muck
    furrymuck:
      host: furrymuck.com
      port: 8899
      ssl: true
      insecure: true
      type: muck
    tapestries:
      host: tapestries.fur.com
      port: 6699
      ssl: true
      insecure: true
      type: muck
    spindizzy:
      host: muck.spindizzy.org
      port: 7073
      ssl: true
      type: muck

  # Settings pertaining to running the client, but not necessarily stuff the user
  # would want to worry about.
  client:

    # Settings pertaining to the logs generated by the client itself.
    syslog:
      # Whether or not to show the system log in a view in the UI.
      show_syslog: false

      # Minimum log level to output (TRACE, DEBUG, INFO, WARNING, ERROR, CRITICAL)
      log_level: INFO

    # Settings pertaining to resource profiling in development. Note that only
    # one of these can be used at a time. If you set more than one to 'true',
    # only the first will be used.
    profile:
      # Whether or not to profile memory usage.
      mem: false

      # Whether or not to profile CPU usage.
      cpu: false

    # Settings pertaining to connectiong logging.
    logging:
      # Date/time format to use. The numbers matter, weirdly enough. The date
      # must follow the reference date/time of 3:04:05PM on January 2nd, 2006,
      # Mountain Standard Time (-0700). 1-2 3:4:5 6 7. It's silly, but I don't
      # make the rules.
      # https://golang.org/pkg/time/#Time.Format
      time_string: 2006-01-02T150405

      # Whether or not to include the date/time messages were received from the
      # server in the default log files.
      log_timestamps: false

      # Whether or not to keep the log for the connection to the world after
      # disconnecting.
      log_world: true
    
    # Settings pertaining to the user interface
    ui:
      # How many lines received from the connection to keep in memory.
      scrollback: 5000

      # How many lines sent to the connection to keep in memory.
      history: 500

      # Whether or not to keep a separate history buffer for each connection
      # or to have one history boffer for all connections.
      unified_history_buffer: true

      # Whether or not to use Vim-style key bindings
      vim_keybindings: false

      # Indentation of wrapped lines.
      indent_first: 0
      indent_subsequent: 4

      # Whether or not to support mouse events
      mouse: false

      # Colors in the UI
      colors:
        send_title:
          # Focused world
          active: "bold+white"
          # Focused world, scrolled up with new activity
          active_more: "bold+underline+white"
          # Non-focused world
          inactive: "steelblue"
          # Non-focused world with new activity
          inactive_more: "steelblue+underline"
          # Disconnected world (non-focused)
          disconnected: "mediumvioletred"
          # Disconnected world with new activity
          disconnected_more: "mediumvioletred+underline"
          # Disconnected world (non-focused) with unread lines
          disconnected_active: "deeppink3"
        modal_title: "bold+cyan"
`
