stimmtausch:
  # This is a basic Stimmtausch configuration file! It contains some handy
  # default settings, as well as some stubbed-out data you'll want to change
  # to suit your own needs. Everything that comes after a '#' is a comment
  # and will be ignored (like these lines!), so you can feel free to delete
  # these or add your own for future reference.
  #
  # All options in the configuration file come as key/value pairs, separated
  # by a ':'. However, you'll notice that these can be nested within each
  # other, rather than just a simple string of characters. This format is
  # called YAML and you can read more about it here: https://yaml.org
  #
  # If YAML isn't your favorite, you can use anything that works with the
  # config file reader we use, Snuffler, which are listed here:
  # https://github.com/makyo/snuffler

  # Worlds are a cobination of a server and a character (think "user", in
  # modern web parlance). The worlds below are just examples. You'll probably
  # want to change them :)
  worlds:
    taps_foxface:
      server: tapestries
      username: foxface
      password: fox_12345
      # You can specify that all output from a world should be logged. it will
      # be logged to files named after the date in
      # $HOME/.config/stimmtausch/worlds/<world>
      # This setting defaults to false.
      log: true
    taps_rudderbutt:
      # You can associate as many characters as you want with a server.
      server: tapestries
      username: rudderbutt
      password: rudder_67890
    furry_foxface:
      # You can include an optional display name for the world which will show
      # up in the UI (though you'll still use the key above to interact with
      # the world). If you don't include this, the key will be used.
      display_name: "Foxface (FM)"
      server: furrymuck
      username: foxface
      password: fox_12345

  # The default world is what is connected to when you run Stimmtausch
  # without specifying a world on the command line.
  default_world: taps_foxface
