name: stimmtausch
base: core18
version: git
summary: Terminal-based MU* client
description: |
  Stimmtausch is a terminal-based MU* client for connecting to multi-user
  online roleplaying games such as MUDs, MUSHes, MUCKs, and MOOs.

grade: stable
confinement: strict

plugs:
  dot-config-stimmtausch:
    interface: personal-files
    read:
      - $HOME/.config/stimmtausch

layout:
  /etc/stimmtausch:
    symlink: $SNAP/etc/stimmtausch

apps:
  stimmtausch:
    command: bin/stimmtausch
    environment:
      HOME: /home/$USER
    plugs:
      - home
      - network
      - config-files
      - share-files
      - log-files

parts:
  stimmtausch:
    plugin: go
    go-packages:
      - github.com/makyo/stimmtausch
    source: .
    source-type: git
    source-branch: snap
  config:
    after: [stimmtausch]
    plugin: dump
    source: _conf/global
    source-type: local
    organize:
      '*': etc/stimmtausch/
