name: stimmtausch
base: core22 # the base snap is the execution environment for this snap
version: git
summary: Terminal-based MU* client
description: |
  Stimmtausch is a terminal-based MU* client for connecting to multi-user
  online roleplaying games such as MUDs, MUSHes, MUCKs, and MOOs.

grade: stable
confinement: strict

plugs:
  dot-config-stimmtausch:
    interface: personal-files
    read:
      - $HOME/.config/stimmtausch

apps:
  stimmtausch:
    command: bin/stimmtausch
    environment:
      HOME: /home/$USER
    plugs:
      - home
      - network
      - dot-config-stimmtausch

parts:
  stimmtausch:
    plugin: go
    source: https://github.com/makyo/stimmtausch
    source-type: git
    build-packages: [golang-go]
